// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tztadwxveljoyoeaakjg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InR6dGFkd3h2ZWxqb3lvZWFha2pnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE1Mzc2MjYsImV4cCI6MjA2NzExMzYyNn0.Exp2Qu6HiQiaeKc-RY07j3f2H3Nl1q51REek1bJeAFY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});