// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hvmhvphflqjwdlgdgudp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imh2bWh2cGhmbHFqd2RsZ2RndWRwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE2ODczMTQsImV4cCI6MjA2NzI2MzMxNH0.Z7dIhp1nKo4TTGCpIPS2Sq8CdmxQJ8zzN44Ax3OM26g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});